ALTER TABLE messages ADD COLUMN IF NOT EXISTS prompt_tokens INT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS completion_tokens INT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS cost NUMERIC(12,6);
